image: node:alpine

variables:
  KUBERNETES_MEMORY_REQUEST: 2Gi
  KUBERNETES_MEMORY_LIMIT: 4Gi

lint:
  script:
    - npm i
    - npm run lint
    - export NODE_OPTIONS=--openssl-legacy-provider
    - npm run build
