
/* eslint-disable object-curly-newline */

// the targets name will be merged with @/common targets-mapping.js file

import { computers, circuits } from '@/common/constants';

const allCompartmentGenericTarget = {
  target: 'AllCompartments',
  type: 'AllCompartments',
  displayName: 'Soma + Dendrites',
};

const hipperpolarizingGenericStim = {
  Stimulus: {
    hypamp: {
      Mode: 'Current',
      Pattern: 'Hyperpolarizing',
      Delay: '0.0',
      Duration: '20000',
    },
  },
  StimulusInject: {
    hypamp_mosaic: {
      Stimulus: 'hypamp',
      Target: 'Mosaic',
    },
  },
};

const runSectionDefaults = {
  // need to keep the PascalCase because goes directly to BlueConfig
  ForwardSkip: 5000,
  Dt: '0.025',
  BaseSeed: '10',
};

const objectStorageBaseURL = 'https://bbp.epfl.ch/public/bsp-resources/sim-launcher-ui';

/*
|--------------------------------------------------------------------------
| Hippocampus Full CA1
|--------------------------------------------------------------------------
*/

const slicesImgBase = `${objectStorageBaseURL}/images-slices-CA1/ca1-20181114`;
const hippoHbpFullCa1 = {
  prefix: { // setting prefix allow to know which computer can run the circuit
    [computers.JURECA]: '/p/home/jusers/antonel1/jureca/vsk2512/CA1/20181114',
    [computers.PIZ_DAINT]: '/apps/hbp/ich002/home/antonel/full_ca1/CA1/20181114',
  },
  paths: {
    MorphologyPath: '<%= prefix %>/entities/morphologies/20180417/',
    METypePath: '<%= prefix %>/entities/emodels/20180504b/hoc',
    CircuitPath: '<%= prefix %>/circuit/',
    nrnPath: '<%= prefix %>/circuit/connectome/functional/',
    MEComboInfoFile: '<%= prefix %>/entities/emodels/20180504b/mecombo_emodel.tsv',
    BioName: '<%= prefix %>/circuit/bioname',
    TargetFile: '<%= prefix %>/circuit/user.target',
    CellLibraryFile: 'circuit.mvd3',
    CurrentDir: '.',
    OutputRoot: '.',
  },
  targets: [
    { name: '5Cells', src: `${slicesImgBase}/5Cells.png`, cells: '5' },
    { name: 'Mosaic', src: `${slicesImgBase}/Mosaic.png`, cells: '456290' },
    { name: 'slice0', displayName: 'Slice 0', src: `${slicesImgBase}/slice0.png`, cells: '1' },
    { name: 'slice1', displayName: 'Slice 01', src: `${slicesImgBase}/slice1.png`, cells: '175' },
    { name: 'slice2', displayName: 'Slice 02', src: `${slicesImgBase}/slice2.png`, cells: '842' },
    { name: 'slice3', displayName: 'Slice 03', src: `${slicesImgBase}/slice3.png`, cells: '1486' },
    { name: 'slice4', displayName: 'Slice 04', src: `${slicesImgBase}/slice4.png`, cells: '2118' },
    { name: 'slice5', displayName: 'Slice 05', src: `${slicesImgBase}/slice5.png`, cells: '2712' },
    { name: 'slice6', displayName: 'Slice 06', src: `${slicesImgBase}/slice6.png`, cells: '3188' },
    { name: 'slice7', displayName: 'Slice 07', src: `${slicesImgBase}/slice7.png`, cells: '3431' },
    { name: 'slice8', displayName: 'Slice 08', src: `${slicesImgBase}/slice8.png`, cells: '3581' },
    { name: 'slice9', displayName: 'Slice 09', src: `${slicesImgBase}/slice9.png`, cells: '3577' },
    { name: 'slice10', displayName: 'Slice 10', src: `${slicesImgBase}/slice10.png`, cells: '3338' },
    { name: 'slice11', displayName: 'Slice 11', src: `${slicesImgBase}/slice11.png`, cells: '3535' },
    { name: 'slice12', displayName: 'Slice 12', src: `${slicesImgBase}/slice12.png`, cells: '3795' },
    { name: 'slice13', displayName: 'Slice 13', src: `${slicesImgBase}/slice13.png`, cells: '4753' },
    { name: 'slice14', displayName: 'Slice 14', src: `${slicesImgBase}/slice14.png`, cells: '5477' },
    { name: 'slice15', displayName: 'Slice 15', src: `${slicesImgBase}/slice15.png`, cells: '6771' },
    { name: 'slice16', displayName: 'Slice 16', src: `${slicesImgBase}/slice16.png`, cells: '6221' },
    { name: 'slice17', displayName: 'Slice 17', src: `${slicesImgBase}/slice17.png`, cells: '6154' },
    { name: 'slice18', displayName: 'Slice 18', src: `${slicesImgBase}/slice18.png`, cells: '6066' },
    { name: 'slice19', displayName: 'Slice 19', src: `${slicesImgBase}/slice19.png`, cells: '6716' },
    { name: 'slice20', displayName: 'Slice 20', src: `${slicesImgBase}/slice20.png`, cells: '6451' },
    { name: 'slice21', displayName: 'Slice 21', src: `${slicesImgBase}/slice21.png`, cells: '6397' },
    { name: 'slice22', displayName: 'Slice 22', src: `${slicesImgBase}/slice22.png`, cells: '6354' },
    { name: 'slice23', displayName: 'Slice 23', src: `${slicesImgBase}/slice23.png`, cells: '6197' },
    { name: 'slice24', displayName: 'Slice 24', src: `${slicesImgBase}/slice24.png`, cells: '6041' },
    { name: 'slice25', displayName: 'Slice 25', src: `${slicesImgBase}/slice25.png`, cells: '5863' },
    { name: 'slice26', displayName: 'Slice 26', src: `${slicesImgBase}/slice26.png`, cells: '6658' },
    { name: 'slice27', displayName: 'Slice 27', src: `${slicesImgBase}/slice27.png`, cells: '7269' },
    { name: 'slice28', displayName: 'Slice 28', src: `${slicesImgBase}/slice28.png`, cells: '7924' },
    { name: 'slice29', displayName: 'Slice 29', src: `${slicesImgBase}/slice29.png`, cells: '8485' },
    { name: 'slice30', displayName: 'Slice 30', src: `${slicesImgBase}/slice30.png`, cells: '8358' },
    { name: 'slice31', displayName: 'Slice 31', src: `${slicesImgBase}/slice31.png`, cells: '8212' },
    { name: 'slice32', displayName: 'Slice 32', src: `${slicesImgBase}/slice32.png`, cells: '7993' },
    { name: 'slice33', displayName: 'Slice 33', src: `${slicesImgBase}/slice33.png`, cells: '7909' },
    { name: 'slice34', displayName: 'Slice 34', src: `${slicesImgBase}/slice34.png`, cells: '8363' },
    { name: 'slice35', displayName: 'Slice 35', src: `${slicesImgBase}/slice35.png`, cells: '8548' },
    { name: 'slice36', displayName: 'Slice 36', src: `${slicesImgBase}/slice36.png`, cells: '8410' },
    { name: 'slice37', displayName: 'Slice 37', src: `${slicesImgBase}/slice37.png`, cells: '8655' },
    { name: 'slice38', displayName: 'Slice 38', src: `${slicesImgBase}/slice38.png`, cells: '8969' },
    { name: 'slice39', displayName: 'Slice 39', src: `${slicesImgBase}/slice39.png`, cells: '9243' },
    { name: 'slice40', displayName: 'Slice 40', src: `${slicesImgBase}/slice40.png`, cells: '9573' },
    { name: 'slice41', displayName: 'Slice 41', src: `${slicesImgBase}/slice41.png`, cells: '9868' },
    { name: 'slice42', displayName: 'Slice 42', src: `${slicesImgBase}/slice42.png`, cells: '9698' },
    { name: 'slice43', displayName: 'Slice 43', src: `${slicesImgBase}/slice43.png`, cells: '9808' },
    { name: 'slice44', displayName: 'Slice 44', src: `${slicesImgBase}/slice44.png`, cells: '9675' },
    { name: 'slice45', displayName: 'Slice 45', src: `${slicesImgBase}/slice45.png`, cells: '9738' },
    { name: 'slice46', displayName: 'Slice 46', src: `${slicesImgBase}/slice46.png`, cells: '9948' },
    { name: 'slice47', displayName: 'Slice 47', src: `${slicesImgBase}/slice47.png`, cells: '9482' },
    { name: 'slice48', displayName: 'Slice 48', src: `${slicesImgBase}/slice48.png`, cells: '8509' },
    { name: 'slice49', displayName: 'Slice 49', src: `${slicesImgBase}/slice49.png`, cells: '8084' },
    { name: 'slice50', displayName: 'Slice 50', src: `${slicesImgBase}/slice50.png`, cells: '8145' },
    { name: 'slice51', displayName: 'Slice 51', src: `${slicesImgBase}/slice51.png`, cells: '8604' },
    { name: 'slice52', displayName: 'Slice 52', src: `${slicesImgBase}/slice52.png`, cells: '8534' },
    { name: 'slice53', displayName: 'Slice 53', src: `${slicesImgBase}/slice53.png`, cells: '8323' },
    { name: 'slice54', displayName: 'Slice 54', src: `${slicesImgBase}/slice54.png`, cells: '8516' },
    { name: 'slice55', displayName: 'Slice 55', src: `${slicesImgBase}/slice55.png`, cells: '8458' },
    { name: 'slice56', displayName: 'Slice 56', src: `${slicesImgBase}/slice56.png`, cells: '9192' },
    { name: 'slice57', displayName: 'Slice 57', src: `${slicesImgBase}/slice57.png`, cells: '9407' },
    { name: 'slice58', displayName: 'Slice 58', src: `${slicesImgBase}/slice58.png`, cells: '8973' },
    { name: 'slice59', displayName: 'Slice 59', src: `${slicesImgBase}/slice59.png`, cells: '8598' },
    { name: 'slice60', displayName: 'Slice 60', src: `${slicesImgBase}/slice60.png`, cells: '8036' },
    { name: 'slice61', displayName: 'Slice 61', src: `${slicesImgBase}/slice61.png`, cells: '7251' },
    { name: 'slice62', displayName: 'Slice 62', src: `${slicesImgBase}/slice62.png`, cells: '5292' },
    { name: 'slice63', displayName: 'Slice 63', src: `${slicesImgBase}/slice63.png`, cells: '4828' },
    { name: 'slice64', displayName: 'Slice 64', src: `${slicesImgBase}/slice64.png`, cells: '4430' },
    { name: 'slice65', displayName: 'Slice 65', src: `${slicesImgBase}/slice65.png`, cells: '4691' },
    { name: 'slice66', displayName: 'Slice 66', src: `${slicesImgBase}/slice66.png`, cells: '5297' },
    { name: 'slice67', displayName: 'Slice 67', src: `${slicesImgBase}/slice67.png`, cells: '4423' },
    { name: 'slice68', displayName: 'Slice 68', src: `${slicesImgBase}/slice68.png`, cells: '3781' },
    { name: 'slice69', displayName: 'Slice 69', src: `${slicesImgBase}/slice69.png`, cells: '704' },
    { name: 'SLM_PPA', displayName: 'SLM_PPA', src: `${slicesImgBase}/SLM_PPA.png`, cells: '330' },
    { name: 'PV', src: `${slicesImgBase}/PV.png`, cells: '17042' },
    { name: 'BS', src: `${slicesImgBase}/BS.png`, cells: '4487' },
    { name: 'BC', src: `${slicesImgBase}/BC.png`, cells: '18303' },
    { name: 'SP_INT', src: `${slicesImgBase}/SP_INT.png`, cells: '42199' },
    { name: 'INT', src: `${slicesImgBase}/INT.png`, cells: '48757' },
    { name: 'cylinders', src: `${slicesImgBase}/cylinders.png`, cells: '24124' },
    { name: 'cylinder205789r200', src: `${slicesImgBase}/cylinder205789r200.png`, cells: '3480' },
    { name: 'cylinder377156r200', src: `${slicesImgBase}/cylinder377156r200.png`, cells: '3511' },
    { name: 'cylinder55853r200', src: `${slicesImgBase}/cylinder55853r200.png`, cells: '2775' },
    { name: 'cylinder405270r200', src: `${slicesImgBase}/cylinder405270r200.png`, cells: '3625' },
    { name: 'cylinder363971r200', src: `${slicesImgBase}/cylinder363971r200.png`, cells: '5517' },
    { name: 'cylinder75751r200', src: `${slicesImgBase}/cylinder75751r200.png`, cells: '4059' },
    { name: 'cylinder367943r200', src: `${slicesImgBase}/cylinder367943r200.png`, cells: '2439' },
    { name: 'slice24502t450', src: `${slicesImgBase}/slice24502t450.png`, cells: '47632' },
    { name: 'slice24502t475', src: `${slicesImgBase}/slice24502t475.png`, cells: '47632' },
    { name: 'slice24502t325', src: `${slicesImgBase}/slice24502t325.png`, cells: '47632' },
    { name: 'slice24502t315', src: `${slicesImgBase}/slice24502t315.png`, cells: '47632' },
    { name: 'Excitatory', src: `${slicesImgBase}/Excitatory.png`, cells: '407533' },
    { name: 'Inhibitory', src: `${slicesImgBase}/Inhibitory.png`, cells: '48757' },
    { name: 'SO_BP', src: `${slicesImgBase}/SO_BP.png`, cells: '309' },
    { name: 'SO_BS', src: `${slicesImgBase}/SO_BS.png`, cells: '1055' },
    { name: 'SO_OLM', src: `${slicesImgBase}/SO_OLM.png`, cells: '3351' },
    { name: 'SO_Tri', src: `${slicesImgBase}/SO_Tri.png`, cells: '1431' },
    { name: 'SP_AA', src: `${slicesImgBase}/SP_AA.png`, cells: '2404' },
    { name: 'SP_BS', src: `${slicesImgBase}/SP_BS.png`, cells: '3432' },
    { name: 'SP_CCKBC', src: `${slicesImgBase}/SP_CCKBC.png`, cells: '7097' },
    { name: 'SP_Ivy', src: `${slicesImgBase}/SP_Ivy.png`, cells: '18060' },
    { name: 'SP_PC', src: `${slicesImgBase}/SP_PC.png`, cells: '407533' },
    { name: 'SP_PVBC', src: `${slicesImgBase}/SP_PVBC.png`, cells: '11206' },
    { name: 'SR_SCA', src: `${slicesImgBase}/SR_SCA.png`, cells: '82' },
    { name: 'bAC', src: `${slicesImgBase}/bAC.png`, cells: '19309' },
    { name: 'cAC', src: `${slicesImgBase}/cAC.png`, cells: '11961' },
    { name: 'cACpyr', src: `${slicesImgBase}/cACpyr.png`, cells: '407533' },
    { name: 'cNAC', src: `${slicesImgBase}/cNAC.png`, cells: '17487' },
    { name: 'SLM', src: `${slicesImgBase}/SLM.png`, cells: '330' },
    { name: 'SP', src: `${slicesImgBase}/SP.png`, cells: '449732' },
    { name: 'SO', src: `${slicesImgBase}/SO.png`, cells: '6146' },
    { name: 'SR', src: `${slicesImgBase}/SR.png`, cells: '82' },
    { name: 'SC', displayName: 'Schaffer Collateral Projection', cells: '' },
  ],
  defaultPopulation: 'slice5',
  biggestTarget: 'Mosaic',
  allCompartmentTargetObj: Object.assign({}, allCompartmentGenericTarget),
  displayName: 'Hippocampus Full CA1',
  hipperpolarizingStim: Object.assign({}, hipperpolarizingGenericStim),
  runSection: Object.assign({}, runSectionDefaults),
};


const hippoBbpFullCa1 = Object.assign(
  {},
  { ...hippoHbpFullCa1 },
  {
    prefix: {
      [computers.BB5]: '/gpfs/bbp.cscs.ch/project/proj42/home/antonel/CA1/20181114',
    },
  },
);

const hippoHbpSAFullCa1 = Object.assign(
  {},
  { ...hippoHbpFullCa1 },
  {
    prefix: {
      [computers.SERVICE_ACCOUNT]: '/apps/hbp/ich002/home/antonel/full_ca1/CA1/20181114',
    },
  },
);

/*
|--------------------------------------------------------------------------
| O1 Hippocampus Microcircuit
|--------------------------------------------------------------------------
*/

const microcircuitImgBase = `${objectStorageBaseURL}/o1-20181114`;
const hippoHbpMicrocircuit = {
  prefix: {
    [computers.JURECA]: '/p/project/cvsk25/vsk2512/O1/20181114',
    [computers.PIZ_DAINT]: '/apps/hbp/ich002/home/antonel/O1/20181114',
  },
  paths: {
    MorphologyPath: '<%= prefix %>/entities/morphologies/20180417/',
    METypePath: '<%= prefix %>/entities/emodels/20180504b/hoc/',
    MEComboInfoFile: '<%= prefix %>/entities/emodels/20180504b/mecombo_emodel.tsv',
    CircuitPath: '<%= prefix %>/circuit/',
    nrnPath: '<%= prefix %>/circuit/connectome/functional/',
    TargetFile: '<%= prefix %>/circuit/user.target',
    CellLibraryFile: 'circuit.mvd3',
    CurrentDir: '.',
    OutputRoot: '.',
  },
  targets: [
    { name: 'Mosaic', src: `${microcircuitImgBase}/Mosaic.png`, cells: '18186' },
    { name: 'All', src: `${microcircuitImgBase}/Mosaic.png`, cells: '18186' },
    { name: 'Random1PercFull', displayName: 'Random 1% full circuit', src: `${microcircuitImgBase}/Random1PercFull.png`, cells: '6' },
    { name: 'Random5PercFull', displayName: 'Random 5% full circuit', src: `${microcircuitImgBase}/Random5PercFull.png`, cells: '13' },
    { name: 'Random10PercFull', displayName: 'Random 10% full circuit', src: `${microcircuitImgBase}/Random10PercFull.png`, cells: '16' },
    { name: 'Random500Central', displayName: 'Random 500 central column', src: `${microcircuitImgBase}/Random500Central.png`, cells: '500' },
    { name: 'Random1KCentral', displayName: 'Random 1K central column', src: `${microcircuitImgBase}/Random1KCentral.png`, cells: '1000' },
    { name: 'Excitatory', src: `${microcircuitImgBase}/Excitatory.png`, cells: '16860' },
    { name: 'Inhibitory', src: `${microcircuitImgBase}/Inhibitory.png`, cells: '1326' },
    { name: 'SLM_PPA', src: `${microcircuitImgBase}/SLM_PPA.png`, cells: '4' },
    { name: 'SO_BP', src: `${microcircuitImgBase}/SO_BP.png`, cells: '2' },
    { name: 'SO_BS', src: `${microcircuitImgBase}/SO_BS.png`, cells: '28' },
    { name: 'SO_OLM', src: `${microcircuitImgBase}/SO_OLM.png`, cells: '88' },
    { name: 'SO_Tri', src: `${microcircuitImgBase}/SO_Tri.png`, cells: '38' },
    { name: 'SP_AA', src: `${microcircuitImgBase}/SP_AA.png`, cells: '80' },
    { name: 'SP_BS', src: `${microcircuitImgBase}/SP_BS.png`, cells: '91' },
    { name: 'SP_CCKBC', src: `${microcircuitImgBase}/SP_CCKBC.png`, cells: '195' },
    { name: 'SP_Ivy', src: `${microcircuitImgBase}/SP_Ivy.png`, cells: '477' },
    { name: 'SP_PC', src: `${microcircuitImgBase}/SP_PC.png`, cells: '16860' },
    { name: 'SP_PVBC', src: `${microcircuitImgBase}/SP_PVBC.png`, cells: '299' },
    { name: 'SR_SCA', src: `${microcircuitImgBase}/SR_SCA.png`, cells: '24' },
    { name: 'bAC', src: `${microcircuitImgBase}/bAC.png`, cells: '529' },
    { name: 'cAC', src: `${microcircuitImgBase}/cAC.png`, cells: '345' },
    { name: 'cACpyr', src: `${microcircuitImgBase}/cACpyr.png`, cells: '16860' },
    { name: 'cNAC', src: `${microcircuitImgBase}/cNAC.png`, cells: '452' },
    { name: 'SR', src: `${microcircuitImgBase}/SR.png`, cells: '24' },
    { name: 'SP', src: `${microcircuitImgBase}/SP.png`, cells: '18002' },
    { name: 'SLM', src: `${microcircuitImgBase}/SLM.png`, cells: '4' },
    { name: 'SO', src: `${microcircuitImgBase}/SO.png`, cells: '156' },
    { name: 'mc0_Column', src: `${microcircuitImgBase}/mc0_Column.png`, cells: '2556' },
    { name: 'mc1_Column', src: `${microcircuitImgBase}/mc1_Column.png`, cells: '2713' },
    { name: 'mc2_Column', src: `${microcircuitImgBase}/mc2_Column.png`, cells: '2495' },
    { name: 'mc3_Column', src: `${microcircuitImgBase}/mc3_Column.png`, cells: '2638' },
    { name: 'mc4_Column', src: `${microcircuitImgBase}/mc4_Column.png`, cells: '2582' },
    { name: 'mc5_Column', src: `${microcircuitImgBase}/mc5_Column.png`, cells: '2638' },
    { name: 'mc6_Column', src: `${microcircuitImgBase}/mc6_Column.png`, cells: '2564' },
    { name: 'SC-Exc', src: `${microcircuitImgBase}/SC-Exc.png`, cells: '' },
    { name: 'PV', src: `${microcircuitImgBase}/PV.png`, cells: '470' },
    { name: 'BS', src: `${microcircuitImgBase}/BS.png`, cells: '119' },
    { name: 'BC', src: `${microcircuitImgBase}/BC.png`, cells: '494' },
    { name: 'SP_INT', src: `${microcircuitImgBase}/SP_INT.png`, cells: '1142' },
    { name: 'INT', src: `${microcircuitImgBase}/INT.png`, cells: '1326' },
    { name: 'Minicolumn', src: `${microcircuitImgBase}/Minicolumn.png`, cells: '2638' },
    { name: 'SC-CA1', displayName: 'Schaffer Collateral Projection', cells: '' },
  ],
  biggestTarget: 'Mosaic',
  defaultPopulation: 'mc2_Column',
  allCompartmentTargetObj: Object.assign({}, allCompartmentGenericTarget),
  displayName: 'Hippocampus CA1 Microcircuit',
  extraParamsInBC: {},
  hipperpolarizingStim: Object.assign({}, hipperpolarizingGenericStim),
  runSection: Object.assign({}, runSectionDefaults),
};


const hippoBbpMicrocircuit = Object.assign(
  {},
  { ...hippoHbpMicrocircuit },
  {
    prefix: {
      [computers.BB5]: '/gpfs/bbp.cscs.ch/project/proj42/home/antonel/O1/20181114',
    },
  },
);

/*
|--------------------------------------------------------------------------
| MOOC Hippocampus Microcircuit
|--------------------------------------------------------------------------
*/

const moocMicrocircuitImgBase = `${objectStorageBaseURL}/O1.20191017`;

const hippoMoocSvcAccMicrocircuit = Object.assign(
  {},
  { ...hippoHbpMicrocircuit },
  {
    prefix: {
      [computers.SERVICE_ACCOUNT]: '/store/hbp/ich002/public/CA1.O1/mooc_sonata_circuit',
    },
    paths: Object.assign(
      {},
      { ...hippoHbpMicrocircuit.paths },
      {
        MorphologyPath: '<%= prefix %>/morphologies/swc/',
        MorphologyType: 'swc',
        METypePath: '<%= prefix %>/emodels/hoc',
        MEComboInfoFile: '<%= prefix %>/emodels/mecombo_emodel.tsv',
        CellLibraryFile: '<%= prefix %>/sonata/nodes/nodes.h5',
        CircuitPath: '<%= prefix %>/',
        nrnPath: '<%= prefix %>/sonata/edges/edges.h5:hippocampus_neurons__hippocampus_neurons__chemical',
        TargetFile: '<%= prefix %>/user.target',
      },
    ),
    targets: [
      { name: 'most_central_50_SP_PC', src: `${moocMicrocircuitImgBase}/most_central_50_SP_PC.png`, cells: '50' },
      { name: 'Full Circuit', src: `${moocMicrocircuitImgBase}/Mosaic.png`, cells: '18198' },
      { name: 'Excitatory', src: `${moocMicrocircuitImgBase}/Excitatory.png`, cells: '16860' },
      { name: 'Inhibitory', src: `${moocMicrocircuitImgBase}/Inhibitory.png`, cells: '1338' },
      { name: 'SLM_PPA', src: `${moocMicrocircuitImgBase}/SLM_PPA.png`, cells: '3' },
      { name: 'SO_BP', src: `${moocMicrocircuitImgBase}/SO_BP.png`, cells: '10' },
      { name: 'SO_BS', src: `${moocMicrocircuitImgBase}/SO_BS.png`, cells: '24' },
      { name: 'SO_OLM', src: `${moocMicrocircuitImgBase}/SO_OLM.png`, cells: '88' },
      { name: 'SO_Tri', src: `${moocMicrocircuitImgBase}/SO_Tri.png`, cells: '38' },
      { name: 'SP_AA', src: `${moocMicrocircuitImgBase}/SP_AA.png`, cells: '80' },
      { name: 'SP_BS', src: `${moocMicrocircuitImgBase}/SP_BS.png`, cells: '91' },
      { name: 'SP_CCKBC', src: `${moocMicrocircuitImgBase}/SP_CCKBC.png`, cells: '195' },
      { name: 'SP_Ivy', src: `${moocMicrocircuitImgBase}/SP_Ivy.png`, cells: '477' },
      { name: 'SP_PC', src: `${moocMicrocircuitImgBase}/SP_PC.png`, cells: '16860' },
      { name: 'SP_PVBC', src: `${moocMicrocircuitImgBase}/SP_PVBC.png`, cells: '299' },
      { name: 'SR_SCA', src: `${moocMicrocircuitImgBase}/SR_SCA.png`, cells: '33' },
      { name: 'bAC', src: `${moocMicrocircuitImgBase}/bAC.png`, cells: '539' },
      { name: 'cAC', src: `${moocMicrocircuitImgBase}/cAC.png`, cells: '354' },
      { name: 'cACpyr', src: `${moocMicrocircuitImgBase}/cACpyr.png`, cells: '16860' },
      { name: 'cNAC', src: `${moocMicrocircuitImgBase}/cNAC.png`, cells: '445' },
      { name: 'mc0;SO', src: `${moocMicrocircuitImgBase}/mc0;SO.png`, cells: '21' },
      { name: 'mc0;SP', src: `${moocMicrocircuitImgBase}/mc0;SP.png`, cells: '2529' },
      { name: 'mc0;SR', src: `${moocMicrocircuitImgBase}/mc0;SR.png`, cells: '3' },
      { name: 'mc1;SO', src: `${moocMicrocircuitImgBase}/mc1;SO.png`, cells: '28' },
      { name: 'mc1;SP', src: `${moocMicrocircuitImgBase}/mc1;SP.png`, cells: '2664' },
      { name: 'mc1;SR', src: `${moocMicrocircuitImgBase}/mc1;SR.png`, cells: '2' },
      { name: 'mc2;SO', src: `${moocMicrocircuitImgBase}/mc2;SO.png`, cells: '15' },
      { name: 'mc2;SP', src: `${moocMicrocircuitImgBase}/mc2;SP.png`, cells: '2466' },
      { name: 'mc2;SR', src: `${moocMicrocircuitImgBase}/mc2;SR.png`, cells: '3' },
      { name: 'mc3;SLM', src: `${moocMicrocircuitImgBase}/mc3;SLM.png`, cells: '1' },
      { name: 'mc3;SO', src: `${moocMicrocircuitImgBase}/mc3;SO.png`, cells: '24' },
      { name: 'mc3;SP', src: `${moocMicrocircuitImgBase}/mc3;SP.png`, cells: '2604' },
      { name: 'mc3;SR', src: `${moocMicrocircuitImgBase}/mc3;SR.png`, cells: '4' },
      { name: 'mc4;SO', src: `${moocMicrocircuitImgBase}/mc4;SO.png`, cells: '21' },
      { name: 'mc4;SP', src: `${moocMicrocircuitImgBase}/mc4;SP.png`, cells: '2569' },
      { name: 'mc4;SR', src: `${moocMicrocircuitImgBase}/mc4;SR.png`, cells: '5' },
      { name: 'mc5;SLM', src: `${moocMicrocircuitImgBase}/mc5;SLM.png`, cells: '1' },
      { name: 'mc5;SO', src: `${moocMicrocircuitImgBase}/mc5;SO.png`, cells: '24' },
      { name: 'mc5;SP', src: `${moocMicrocircuitImgBase}/mc5;SP.png`, cells: '2630' },
      { name: 'mc5;SR', src: `${moocMicrocircuitImgBase}/mc5;SR.png`, cells: '9' },
      { name: 'mc6;SLM', src: `${moocMicrocircuitImgBase}/mc6;SLM.png`, cells: '1' },
      { name: 'mc6;SO', src: `${moocMicrocircuitImgBase}/mc6;SO.png`, cells: '27' },
      { name: 'mc6;SP', src: `${moocMicrocircuitImgBase}/mc6;SP.png`, cells: '2540' },
      { name: 'mc6;SR', src: `${moocMicrocircuitImgBase}/mc6;SR.png`, cells: '7' },
      { name: 'mc0_Column', src: `${moocMicrocircuitImgBase}/mc0_Column.png`, cells: '2553' },
      { name: 'mc1_Column', src: `${moocMicrocircuitImgBase}/mc1_Column.png`, cells: '2694' },
      { name: 'mc2_Column', src: `${moocMicrocircuitImgBase}/mc2_Column.png`, cells: '2484' },
      { name: 'mc3_Column', src: `${moocMicrocircuitImgBase}/mc3_Column.png`, cells: '2633' },
      { name: 'mc4_Column', src: `${moocMicrocircuitImgBase}/mc4_Column.png`, cells: '2595' },
      { name: 'mc5_Column', src: `${moocMicrocircuitImgBase}/mc5_Column.png`, cells: '2664' },
      { name: 'mc6_Column', src: `${moocMicrocircuitImgBase}/mc6_Column.png`, cells: '2575' },
      { name: 'SLM', src: `${moocMicrocircuitImgBase}/SLM.png`, cells: '3' },
      { name: 'SO', src: `${moocMicrocircuitImgBase}/SO.png`, cells: '160' },
      { name: 'SP', src: `${moocMicrocircuitImgBase}/SP.png`, cells: '18002' },
      { name: 'SR', src: `${moocMicrocircuitImgBase}/SR.png`, cells: '33' },
      { name: 'SOM', src: `${moocMicrocircuitImgBase}/SOM.png`, cells: '160' },
      { name: 'CCK', src: `${moocMicrocircuitImgBase}/CCK.png`, cells: '231' },
      { name: 'PV', src: `${moocMicrocircuitImgBase}/PV.png`, cells: '470' },
      { name: 'BC', src: `${moocMicrocircuitImgBase}/BC.png`, cells: '494' },
      { name: 'BS', src: `${moocMicrocircuitImgBase}/BS.png`, cells: '115' },
      { name: 'CA3_PC', displayName: 'CA3 Projection', cells: '' },
    ],
    displayName: 'Hippocampus MOOC Service Account Microcircuit',
    biggestTarget: 'Full Circuit',
    isSonata: true,
    sonataNeuronsPopulation: 'hippocampus_neurons',
    runSection: Object.assign(
      {},
      runSectionDefaults,
      {
        NumSynapseFiles: 2048,
        RNGMode: 'Random123',
        Simulator: 'CORENEURON',
        BaseSeed: '264118',
        RunMode: 'LoadBalance',
      },
    ),
  },
);

/*
|--------------------------------------------------------------------------
| O1 SSCx
|--------------------------------------------------------------------------
*/

const sscxImgBase = `${objectStorageBaseURL}/sscx-o1.v6a-20171212`;
const sscxBbpMicrocircuit = {
  prefix: {
    [computers.BB5]: '',
  },
  paths: {
    MorphologyPath: '<%= prefix %>/gpfs/bbp.cscs.ch/project/proj59/entities/morphologies/2017.10.31',
    METypePath: '<%= prefix %>/gpfs/bbp.cscs.ch/project/proj64/home/vangeit/modelmanagement/prod.20171103/mm_runs/run/1810912/output/emodels_hoc/',
    MEComboInfoFile: '<%= prefix %>/gpfs/bbp.cscs.ch/project/proj64/home/vangeit/modelmanagement/prod.20171103/megate_runs/run/6c6d611/output_select/mecombo_emodel.tsv',
    CircuitPath: '<%= prefix %>/gpfs/bbp.cscs.ch/project/proj64/circuits/O1.v6a/20171212/',
    nrnPath: '<%= prefix %>/gpfs/bbp.cscs.ch/project/proj64/circuits/O1.v6a/20171212/ncsFunctionalAllRecipePathways',
    TargetFile: '<%= prefix %>/gpfs/bbp.cscs.ch/home/antonel/sscx/user.target',
    CellLibraryFile: 'circuit.mvd3',
    CurrentDir: '.',
    OutputRoot: '.',
  },
  targets: [
    { name: '5Cells', src: `${sscxImgBase}/5Cells.png`, cells: '5' },
    { name: 'Mosaic', src: `${sscxImgBase}/Mosaic.png`, cells: '162048' },
    { name: 'Excitatory', src: `${sscxImgBase}/Excitatory.png`, cells: '141249' },
    { name: 'Inhibitory', src: `${sscxImgBase}/Inhibitory.png`, cells: '20799' },
    { name: 'Layer1', src: `${sscxImgBase}/Layer1.png`, cells: '1784' },
    { name: 'Layer2', src: `${sscxImgBase}/Layer2.png`, cells: '14647' },
    { name: 'Layer3', src: `${sscxImgBase}/Layer3.png`, cells: '26561' },
    { name: 'Layer4', src: `${sscxImgBase}/Layer4.png`, cells: '24805' },
    { name: 'Layer5', src: `${sscxImgBase}/Layer5.png`, cells: '34618' },
    { name: 'Layer6', src: `${sscxImgBase}/Layer6.png`, cells: '59633' },
    { name: 'L1_DAC', src: `${sscxImgBase}/L1_DAC.png`, cells: '289' },
    { name: 'L1_HAC', src: `${sscxImgBase}/L1_HAC.png`, cells: '456' },
    { name: 'L1_LAC', src: `${sscxImgBase}/L1_LAC.png`, cells: '152' },
    { name: 'L1_NGC-DA', src: `${sscxImgBase}/L1_NGC-DA.png`, cells: '400' },
    { name: 'L1_NGC-SA', src: `${sscxImgBase}/L1_NGC-SA.png`, cells: '291' },
    { name: 'L1_SAC', src: `${sscxImgBase}/L1_SAC.png`, cells: '196' },
    { name: 'L23_BP', src: `${sscxImgBase}/L23_BP.png`, cells: '382' },
    { name: 'L23_BTC', src: `${sscxImgBase}/L23_BTC.png`, cells: '647' },
    { name: 'L23_CHC', src: `${sscxImgBase}/L23_CHC.png`, cells: '94' },
    { name: 'L23_DBC', src: `${sscxImgBase}/L23_DBC.png`, cells: '395' },
    { name: 'L23_LBC', src: `${sscxImgBase}/L23_LBC.png`, cells: '1718' },
    { name: 'L23_MC', src: `${sscxImgBase}/L23_MC.png`, cells: '1131' },
    { name: 'L23_NBC', src: `${sscxImgBase}/L23_NBC.png`, cells: '1097' },
    { name: 'L23_NGC', src: `${sscxImgBase}/L23_NGC.png`, cells: '184' },
    { name: 'L23_SBC', src: `${sscxImgBase}/L23_SBC.png`, cells: '357' },
    { name: 'L2_IPC', src: `${sscxImgBase}/L2_IPC.png`, cells: '977' },
    { name: 'L2_TPC:A', src: `${sscxImgBase}/L2_TPC-A.png`, cells: '1572' },
    { name: 'L2_TPC:B', src: `${sscxImgBase}/L2_TPC-B.png`, cells: '9819' },
    { name: 'L3_TPC:A', src: `${sscxImgBase}/L3_TPC-A.png`, cells: '17741' },
    { name: 'L3_TPC:B', src: `${sscxImgBase}/L3_TPC-B.png`, cells: '5094' },
    { name: 'L4_BP', src: `${sscxImgBase}/L4_BP.png`, cells: '80' },
    { name: 'L4_BTC', src: `${sscxImgBase}/L4_BTC.png`, cells: '180' },
    { name: 'L4_CHC', src: `${sscxImgBase}/L4_CHC.png`, cells: '14' },
    { name: 'L4_DBC', src: `${sscxImgBase}/L4_DBC.png`, cells: '81' },
    { name: 'L4_LBC', src: `${sscxImgBase}/L4_LBC.png`, cells: '511' },
    { name: 'L4_MC', src: `${sscxImgBase}/L4_MC.png`, cells: '375' },
    { name: 'L4_NBC', src: `${sscxImgBase}/L4_NBC.png`, cells: '343' },
    { name: 'L4_NGC', src: `${sscxImgBase}/L4_NGC.png`, cells: '37' },
    { name: 'L4_SBC', src: `${sscxImgBase}/L4_SBC.png`, cells: '77' },
    { name: 'L4_SSC', src: `${sscxImgBase}/L4_SSC.png`, cells: '2069' },
    { name: 'L4_TPC', src: `${sscxImgBase}/L4_TPC.png`, cells: '14921' },
    { name: 'L4_UPC', src: `${sscxImgBase}/L4_UPC.png`, cells: '6117' },
    { name: 'L5_BP', src: `${sscxImgBase}/L5_BP.png`, cells: '178' },
    { name: 'L5_BTC', src: `${sscxImgBase}/L5_BTC.png`, cells: '846' },
    { name: 'L5_CHC', src: `${sscxImgBase}/L5_CHC.png`, cells: '40' },
    { name: 'L5_DBC', src: `${sscxImgBase}/L5_DBC.png`, cells: '205' },
    { name: 'L5_LBC', src: `${sscxImgBase}/L5_LBC.png`, cells: '1838' },
    { name: 'L5_MC', src: `${sscxImgBase}/L5_MC.png`, cells: '766' },
    { name: 'L5_NBC', src: `${sscxImgBase}/L5_NBC.png`, cells: '1251' },
    { name: 'L5_NGC', src: `${sscxImgBase}/L5_NGC.png`, cells: '158' },
    { name: 'L5_SBC', src: `${sscxImgBase}/L5_SBC.png`, cells: '176' },
    { name: 'L5_TPC:A', src: `${sscxImgBase}/L5_TPC-A.png`, cells: '13838' },
    { name: 'L5_TPC:B', src: `${sscxImgBase}/L5_TPC-B.png`, cells: '11265' },
    { name: 'L5_TPC:C', src: `${sscxImgBase}/L5_TPC-C.png`, cells: '2008' },
    { name: 'L5_UPC', src: `${sscxImgBase}/L5_UPC.png`, cells: '2049' },
    { name: 'L6_BP', src: `${sscxImgBase}/L6_BP.png`, cells: '243' },
    { name: 'L6_BPC', src: `${sscxImgBase}/L6_BPC.png`, cells: '9674' },
    { name: 'L6_BTC', src: `${sscxImgBase}/L6_BTC.png`, cells: '584' },
    { name: 'L6_CHC', src: `${sscxImgBase}/L6_CHC.png`, cells: '152' },
    { name: 'L6_DBC', src: `${sscxImgBase}/L6_DBC.png`, cells: '350' },
    { name: 'L6_HPC', src: `${sscxImgBase}/L6_HPC.png`, cells: '8846' },
    { name: 'L6_IPC', src: `${sscxImgBase}/L6_IPC.png`, cells: '12230' },
    { name: 'L6_LBC', src: `${sscxImgBase}/L6_LBC.png`, cells: '1647' },
    { name: 'L6_MC', src: `${sscxImgBase}/L6_MC.png`, cells: '1334' },
    { name: 'L6_NBC', src: `${sscxImgBase}/L6_NBC.png`, cells: '1062' },
    { name: 'L6_NGC', src: `${sscxImgBase}/L6_NGC.png`, cells: '177' },
    { name: 'L6_SBC', src: `${sscxImgBase}/L6_SBC.png`, cells: '305' },
    { name: 'L6_TPC:A', src: `${sscxImgBase}/L6_TPC-A.png`, cells: '10428' },
    { name: 'L6_TPC:C', src: `${sscxImgBase}/L6_TPC-C.png`, cells: '7000' },
    { name: 'L6_UPC', src: `${sscxImgBase}/L6_UPC.png`, cells: '5601' },
    { name: 'bAC', src: `${sscxImgBase}/bAC.png`, cells: '1758' },
    { name: 'bIR', src: `${sscxImgBase}/bIR.png`, cells: '1762' },
    { name: 'bNAC', src: `${sscxImgBase}/bNAC.png`, cells: '1656' },
    { name: 'bSTUT', src: `${sscxImgBase}/bSTUT.png`, cells: '888' },
    { name: 'cACint', src: `${sscxImgBase}/cACint.png`, cells: '5644' },
    { name: 'cADpyr', src: `${sscxImgBase}/cADpyr.png`, cells: '141249' },
    { name: 'cIR', src: `${sscxImgBase}/cIR.png`, cells: '499' },
    { name: 'cNAC', src: `${sscxImgBase}/cNAC.png`, cells: '4358' },
    { name: 'cSTUT', src: `${sscxImgBase}/cSTUT.png`, cells: '1349' },
    { name: 'dNAC', src: `${sscxImgBase}/dNAC.png`, cells: '2202' },
    { name: 'dSTUT', src: `${sscxImgBase}/dSTUT.png`, cells: '683' },
    { name: 'mc0_Column', src: `${sscxImgBase}/mc0_Column.png`, cells: '23081' },
    { name: 'mc1_Column', src: `${sscxImgBase}/mc1_Column.png`, cells: '23266' },
    { name: 'mc2_Column', src: `${sscxImgBase}/mc2_Column.png`, cells: '22295' },
    { name: 'mc3_Column', src: `${sscxImgBase}/mc3_Column.png`, cells: '23422' },
    { name: 'mc4_Column', src: `${sscxImgBase}/mc4_Column.png`, cells: '23240' },
    { name: 'mc5_Column', src: `${sscxImgBase}/mc5_Column.png`, cells: '23272' },
    { name: 'mc6_Column', src: `${sscxImgBase}/mc6_Column.png`, cells: '23472' },
    { name: 'INH_OTHER', src: `${sscxImgBase}/INH_OTHER.png`, cells: '2188' },
    { name: 'L23_PC', src: `${sscxImgBase}/L23_PC.png`, cells: '34226' },
    { name: 'L5_TTPC1', src: `${sscxImgBase}/L5_TTPC1.png`, cells: '13838' },
    { name: 'L5_TTPC2', src: `${sscxImgBase}/L5_TTPC2.png`, cells: '11265' },
    { name: 'PV_FS', src: `${sscxImgBase}/PV_FS.png`, cells: '10682' },
    { name: 'DISTAR_INH', src: `${sscxImgBase}/DISTAR_INH.png`, cells: '7777' },
    { name: 'Layer23', src: `${sscxImgBase}/Layer23.png`, cells: '41208' },
    { name: 'Layer45', src: `${sscxImgBase}/Layer45.png`, cells: '59423' },
    { name: 'L5_TPC_AB', src: `${sscxImgBase}/L5_TPC_AB.png`, cells: '25103' },
    { name: 'L5_BC', src: `${sscxImgBase}/L5_BC.png`, cells: '3265' },
    { name: 'CHC', src: `${sscxImgBase}/CHC.png`, cells: '300' },
    { name: 'BC', src: `${sscxImgBase}/BC.png`, cells: '10382' },
    { name: 'MC', src: `${sscxImgBase}/MC.png`, cells: '3606' },
    { name: 'DBC', src: `${sscxImgBase}/DBC.png`, cells: '1031' },
    { name: 'BTC', src: `${sscxImgBase}/BTC.png`, cells: '2257' },
    { name: 'BP', src: `${sscxImgBase}/BP.png`, cells: '883' },
    { name: 'L23_NBC_LBC', src: `${sscxImgBase}/L23_NBC_LBC.png`, cells: '2815' },
    { name: 'Inh_not_LBC_NBC', src: `${sscxImgBase}/Inh_not_LBC_NBC.png`, cells: '11332' },
    { name: 'NGC_not_L1', src: `${sscxImgBase}/NGC_not_L1.png`, cells: '556' },
    { name: 'Other_Inh', src: `${sscxImgBase}/Other_Inh.png`, cells: '2340' },
    { name: 'LBC', src: `${sscxImgBase}/LBC.png`, cells: '5714' },
    { name: 'NBC', src: `${sscxImgBase}/NBC.png`, cells: '3753' },
    { name: 'LBC_NBC', src: `${sscxImgBase}/LBC_NBC.png`, cells: '9467' },
    { name: 'Layer2Excitatory', src: `${sscxImgBase}/Layer2Excitatory.png`, cells: '12368' },
    { name: 'Layer3Excitatory', src: `${sscxImgBase}/Layer3Excitatory.png`, cells: '22835' },
    { name: 'Layer23Excitatory', src: `${sscxImgBase}/Layer23Excitatory.png`, cells: '35203' },
    { name: 'Layer4Excitatory', src: `${sscxImgBase}/Layer4Excitatory.png`, cells: '23107' },
    { name: 'Layer5Excitatory', src: `${sscxImgBase}/Layer5Excitatory.png`, cells: '29160' },
    { name: 'Layer6Excitatory', src: `${sscxImgBase}/Layer6Excitatory.png`, cells: '53779' },
    { name: 'dNAC_dSTUT', src: `${sscxImgBase}/dNAC_dSTUT.png`, cells: '2885' },
    { name: 'Inhibitory_no_dNAC_dSTUT', src: `${sscxImgBase}/Inhibitory_no_dNAC_dSTUT.png`, cells: '17914' },
    { name: 'proj_Thalamocortical_VPM_Source', cells: '' },
  ],
  biggestTarget: 'Mosaic',
  defaultPopulation: 'mc2_Column',
  allCompartmentTargetObj: Object.assign({}, allCompartmentGenericTarget),
  displayName: 'SomatosensoryCortex Microcircuit',
  extraParamsInBC: {},
  hipperpolarizingStim: Object.assign({}, hipperpolarizingGenericStim),
  runSection: Object.assign({}, runSectionDefaults),
};


/*
|--------------------------------------------------------------------------
| O1 SSCx Mouse 2018
|--------------------------------------------------------------------------
*/

const sscxO1Mouse2018ImgBase = `${objectStorageBaseURL}/sscx-o1-mouse-20180305`;
const sscxHbpSAMouseMicrocircuit = {
  prefix: {
    [computers.SERVICE_ACCOUNT]: '/store/hbp/ich002/public/mouse_sscx_o1/sonata_2018_20200330',
  },
  paths: {
    MorphologyPath: '<%= prefix %>/entities/morphologies/2018.02.16',
    METypePath: '<%= prefix %>/entities/emodels/2018.02.26.dev0/hoc',
    MEComboInfoFile: '<%= prefix %>/entities/emodels/2018.02.26.dev0/mecombo_emodel.tsv',
    CircuitPath: '<%= prefix %>/circuit',
    nrnPath: '<%= prefix %>/circuit/connectome/functional/edges.sonata',
    CellLibraryFile: 'circuit.mvd3',
    TargetFile: '<%= prefix %>/circuit/user.target',
    CurrentDir: '.',
    OutputRoot: '.',
  },
  targets: [
    { name: '5Cells', src: `${sscxO1Mouse2018ImgBase}/5Cells.png`, cells: '5' },
    { name: 'Mosaic', src: `${sscxO1Mouse2018ImgBase}/Mosaic.png`, cells: '45891' },
    { name: 'All', src: `${sscxO1Mouse2018ImgBase}/All.png`, cells: '45891' },
    { name: 'Excitatory', src: `${sscxO1Mouse2018ImgBase}/Excitatory.png`, cells: '40177' },
    { name: 'Inhibitory', src: `${sscxO1Mouse2018ImgBase}/Inhibitory.png`, cells: '5714' },
    { name: 'L1_DAC', src: `${sscxO1Mouse2018ImgBase}/L1_DAC.png`, cells: '103' },
    { name: 'L1_HAC', src: `${sscxO1Mouse2018ImgBase}/L1_HAC.png`, cells: '202' },
    { name: 'L1_LAC', src: `${sscxO1Mouse2018ImgBase}/L1_LAC.png`, cells: '49' },
    { name: 'L1_NGC-DA', src: `${sscxO1Mouse2018ImgBase}/L1_NGC-DA.png`, cells: '140' },
    { name: 'L1_NGC-SA', src: `${sscxO1Mouse2018ImgBase}/L1_NGC-SA.png`, cells: '140' },
    { name: 'L1_SAC', src: `${sscxO1Mouse2018ImgBase}/L1_SAC.png`, cells: '118' },
    { name: 'L23_BP', src: `${sscxO1Mouse2018ImgBase}/L23_BP.png`, cells: '17' },
    { name: 'L23_BTC', src: `${sscxO1Mouse2018ImgBase}/L23_BTC.png`, cells: '27' },
    { name: 'L23_CHC', src: `${sscxO1Mouse2018ImgBase}/L23_CHC.png`, cells: '238' },
    { name: 'L23_DBC', src: `${sscxO1Mouse2018ImgBase}/L23_DBC.png`, cells: '108' },
    { name: 'L23_LBC', src: `${sscxO1Mouse2018ImgBase}/L23_LBC.png`, cells: '343' },
    { name: 'L23_MC', src: `${sscxO1Mouse2018ImgBase}/L23_MC.png`, cells: '307' },
    { name: 'L23_NBC', src: `${sscxO1Mouse2018ImgBase}/L23_NBC.png`, cells: '187' },
    { name: 'L23_NGC', src: `${sscxO1Mouse2018ImgBase}/L23_NGC.png`, cells: '93' },
    { name: 'L23_SBC', src: `${sscxO1Mouse2018ImgBase}/L23_SBC.png`, cells: '72' },
    { name: 'L2_IPC', src: `${sscxO1Mouse2018ImgBase}/L2_IPC.png`, cells: '426' },
    { name: 'L2_TPC:A', src: `${sscxO1Mouse2018ImgBase}/L2_TPC:A.png`, cells: '654' },
    { name: 'L2_TPC:B', src: `${sscxO1Mouse2018ImgBase}/L2_TPC:B.png`, cells: '3893' },
    { name: 'L3_TPC:A', src: `${sscxO1Mouse2018ImgBase}/L3_TPC:A.png`, cells: '3760' },
    { name: 'L3_TPC:B', src: `${sscxO1Mouse2018ImgBase}/L3_TPC:B.png`, cells: '1108' },
    { name: 'L4_BP', src: `${sscxO1Mouse2018ImgBase}/L4_BP.png`, cells: '3' },
    { name: 'L4_BTC', src: `${sscxO1Mouse2018ImgBase}/L4_BTC.png`, cells: '26' },
    { name: 'L4_CHC', src: `${sscxO1Mouse2018ImgBase}/L4_CHC.png`, cells: '4' },
    { name: 'L4_DBC', src: `${sscxO1Mouse2018ImgBase}/L4_DBC.png`, cells: '47' },
    { name: 'L4_LBC', src: `${sscxO1Mouse2018ImgBase}/L4_LBC.png`, cells: '138' },
    { name: 'L4_MC', src: `${sscxO1Mouse2018ImgBase}/L4_MC.png`, cells: '167' },
    { name: 'L4_NBC', src: `${sscxO1Mouse2018ImgBase}/L4_NBC.png`, cells: '150' },
    { name: 'L4_NGC', src: `${sscxO1Mouse2018ImgBase}/L4_NGC.png`, cells: '7' },
    { name: 'L4_SBC', src: `${sscxO1Mouse2018ImgBase}/L4_SBC.png`, cells: '83' },
    { name: 'L4_SSC', src: `${sscxO1Mouse2018ImgBase}/L4_SSC.png`, cells: '723' },
    { name: 'L4_TPC', src: `${sscxO1Mouse2018ImgBase}/L4_TPC.png`, cells: '4836' },
    { name: 'L4_UPC', src: `${sscxO1Mouse2018ImgBase}/L4_UPC.png`, cells: '2020' },
    { name: 'L5_BP', src: `${sscxO1Mouse2018ImgBase}/L5_BP.png`, cells: '40' },
    { name: 'L5_BTC', src: `${sscxO1Mouse2018ImgBase}/L5_BTC.png`, cells: '129' },
    { name: 'L5_CHC', src: `${sscxO1Mouse2018ImgBase}/L5_CHC.png`, cells: '19' },
    { name: 'L5_DBC', src: `${sscxO1Mouse2018ImgBase}/L5_DBC.png`, cells: '121' },
    { name: 'L5_LBC', src: `${sscxO1Mouse2018ImgBase}/L5_LBC.png`, cells: '330' },
    { name: 'L5_MC', src: `${sscxO1Mouse2018ImgBase}/L5_MC.png`, cells: '539' },
    { name: 'L5_NBC', src: `${sscxO1Mouse2018ImgBase}/L5_NBC.png`, cells: '348' },
    { name: 'L5_NGC', src: `${sscxO1Mouse2018ImgBase}/L5_NGC.png`, cells: '15' },
    { name: 'L5_SBC', src: `${sscxO1Mouse2018ImgBase}/L5_SBC.png`, cells: '50' },
    { name: 'L5_TPC:A', src: `${sscxO1Mouse2018ImgBase}/L5_TPC:A.png`, cells: '3843' },
    { name: 'L5_TPC:B', src: `${sscxO1Mouse2018ImgBase}/L5_TPC:B.png`, cells: '3148' },
    { name: 'L5_TPC:C', src: `${sscxO1Mouse2018ImgBase}/L5_TPC:C.png`, cells: '567' },
    { name: 'L5_UPC', src: `${sscxO1Mouse2018ImgBase}/L5_UPC.png`, cells: '562' },
    { name: 'L6_BP', src: `${sscxO1Mouse2018ImgBase}/L6_BP.png`, cells: '72' },
    { name: 'L6_BPC', src: `${sscxO1Mouse2018ImgBase}/L6_BPC.png`, cells: '2699' },
    { name: 'L6_BTC', src: `${sscxO1Mouse2018ImgBase}/L6_BTC.png`, cells: '64' },
    { name: 'L6_CHC', src: `${sscxO1Mouse2018ImgBase}/L6_CHC.png`, cells: '9' },
    { name: 'L6_DBC', src: `${sscxO1Mouse2018ImgBase}/L6_DBC.png`, cells: '19' },
    { name: 'L6_HPC', src: `${sscxO1Mouse2018ImgBase}/L6_HPC.png`, cells: '2414' },
    { name: 'L6_IPC', src: `${sscxO1Mouse2018ImgBase}/L6_IPC.png`, cells: '3266' },
    { name: 'L6_LBC', src: `${sscxO1Mouse2018ImgBase}/L6_LBC.png`, cells: '580' },
    { name: 'L6_MC', src: `${sscxO1Mouse2018ImgBase}/L6_MC.png`, cells: '310' },
    { name: 'L6_NBC', src: `${sscxO1Mouse2018ImgBase}/L6_NBC.png`, cells: '225' },
    { name: 'L6_NGC', src: `${sscxO1Mouse2018ImgBase}/L6_NGC.png`, cells: '12' },
    { name: 'L6_SBC', src: `${sscxO1Mouse2018ImgBase}/L6_SBC.png`, cells: '63' },
    { name: 'L6_TPC:A', src: `${sscxO1Mouse2018ImgBase}/L6_TPC:A.png`, cells: '2808' },
    { name: 'L6_TPC:C', src: `${sscxO1Mouse2018ImgBase}/L6_TPC:C.png`, cells: '1956' },
    { name: 'L6_UPC', src: `${sscxO1Mouse2018ImgBase}/L6_UPC.png`, cells: '1494' },
    { name: 'bAC', src: `${sscxO1Mouse2018ImgBase}/bAC.png`, cells: '539' },
    { name: 'bIR', src: `${sscxO1Mouse2018ImgBase}/bIR.png`, cells: '535' },
    { name: 'bNAC', src: `${sscxO1Mouse2018ImgBase}/bNAC.png`, cells: '466' },
    { name: 'bSTUT', src: `${sscxO1Mouse2018ImgBase}/bSTUT.png`, cells: '255' },
    { name: 'cACint', src: `${sscxO1Mouse2018ImgBase}/cACint.png`, cells: '1440' },
    { name: 'cADpyr', src: `${sscxO1Mouse2018ImgBase}/cADpyr.png`, cells: '40177' },
    { name: 'cIR', src: `${sscxO1Mouse2018ImgBase}/cIR.png`, cells: '141' },
    { name: 'cNAC', src: `${sscxO1Mouse2018ImgBase}/cNAC.png`, cells: '1358' },
    { name: 'cSTUT', src: `${sscxO1Mouse2018ImgBase}/cSTUT.png`, cells: '322' },
    { name: 'dNAC', src: `${sscxO1Mouse2018ImgBase}/dNAC.png`, cells: '512' },
    { name: 'dSTUT', src: `${sscxO1Mouse2018ImgBase}/dSTUT.png`, cells: '146' },
    { name: 'L1', src: `${sscxO1Mouse2018ImgBase}/L1.png`, cells: '752' },
    { name: 'L2', src: `${sscxO1Mouse2018ImgBase}/L2.png`, cells: '5893' },
    { name: 'L3', src: `${sscxO1Mouse2018ImgBase}/L3.png`, cells: '5340' },
    { name: 'L4', src: `${sscxO1Mouse2018ImgBase}/L4.png`, cells: '8204' },
    { name: 'L5', src: `${sscxO1Mouse2018ImgBase}/L5.png`, cells: '9711' },
    { name: 'L6', src: `${sscxO1Mouse2018ImgBase}/L6.png`, cells: '15991' },
    { name: 'Layer1', src: `${sscxO1Mouse2018ImgBase}/Layer1.png`, cells: '752' },
    { name: 'Layer2', src: `${sscxO1Mouse2018ImgBase}/Layer2.png`, cells: '5893' },
    { name: 'Layer3', src: `${sscxO1Mouse2018ImgBase}/Layer3.png`, cells: '5340' },
    { name: 'Layer4', src: `${sscxO1Mouse2018ImgBase}/Layer4.png`, cells: '8204' },
    { name: 'Layer5', src: `${sscxO1Mouse2018ImgBase}/Layer5.png`, cells: '9711' },
    { name: 'Layer6', src: `${sscxO1Mouse2018ImgBase}/Layer6.png`, cells: '15991' },
    { name: 'mc0_Column', src: `${sscxO1Mouse2018ImgBase}/mc0_Column.png`, cells: '6462' },
    { name: 'mc1_Column', src: `${sscxO1Mouse2018ImgBase}/mc1_Column.png`, cells: '6568' },
    { name: 'mc2_Column', src: `${sscxO1Mouse2018ImgBase}/mc2_Column.png`, cells: '6206' },
    { name: 'mc3_Column', src: `${sscxO1Mouse2018ImgBase}/mc3_Column.png`, cells: '6591' },
    { name: 'mc4_Column', src: `${sscxO1Mouse2018ImgBase}/mc4_Column.png`, cells: '6740' },
    { name: 'mc5_Column', src: `${sscxO1Mouse2018ImgBase}/mc5_Column.png`, cells: '6665' },
    { name: 'mc6_Column', src: `${sscxO1Mouse2018ImgBase}/mc6_Column.png`, cells: '6659' },
    { name: 'proj_Thalamocortical_VPM_Source', cells: '' },
  ],
  biggestTarget: 'Mosaic',
  defaultPopulation: 'mc2_Column',
  allCompartmentTargetObj: Object.assign({}, allCompartmentGenericTarget),
  displayName: 'SomatosensoryCortex Microcircuit',
  extraParamsInBC: {},
  hipperpolarizingStim: Object.assign({}, hipperpolarizingGenericStim),
  runSection: Object.assign({}, runSectionDefaults),
};

const dynamicCircuit = {};

const mapCircuitNameWithUrl = {
  [circuits.HIPPO_HBP_MICROCIRCUIT]: hippoHbpMicrocircuit,
  [circuits.HIPPO_MOOC_SA_MICROCIRCUIT]: hippoMoocSvcAccMicrocircuit,
  [circuits.HIPPO_HBP_FULL_CA1]: hippoHbpFullCa1,
  [circuits.HIPPO_BBP_FULL_CA1]: hippoBbpFullCa1,
  [circuits.HIPPO_HBP_SA_FULL_CA1]: hippoHbpSAFullCa1,
  [circuits.HIPPO_BBP_MICROCIRCUIT]: hippoBbpMicrocircuit,
  [circuits.SSCX_BBP_MICROCIRCUIT]: sscxBbpMicrocircuit,
  [circuits.SSCX_HBP_SA_MOUSE_MICROCIRCUIT]: sscxHbpSAMouseMicrocircuit,
  [circuits.HBP_DYNAMIC_CIRCUIT]: dynamicCircuit,
  [circuits.BBP_DYNAMIC_CIRCUIT]: dynamicCircuit,
};

export default {
  mapCircuitNameWithUrl,
};
