
import constants from '@/common/constants';

export default {
  [constants.areas.HIPPOCAMPUS]: {
    [constants.computers.JURECA]: {
      script: [
        '#!/bin/sh',
        'module --force purge all',
        'module use /usr/local/software/jurecabooster/OtherStages',
        'module load Architecture/KNL',
        'module load Stages/2019a',
        'module load GCC Python/2.7.16',
        'module load Intel ParaStationMPI/5.2.2-1-mt imkl',
        'module load HDF5',
        'export MODULEPATH=$MODULEPATH:/p/project/cvsk25/software-deployment/HBP/jureca-booster/install/latest',
        'module load neurodamus-hippocampus/0.2',
        'export FULL_CPU_PER_NODE=68',
        'python /p/project/cvsk25/vsk2512/simulation/simulation_launch_no_usertarget.py -vv --blueconfig BlueConfig',
      ],
      runtime: 3600,
      nodes: 3,
      cpus: 68,
      partitions: { vsk25: 'booster' },
      executable: '/bin/bash input.sh',
    },
    [constants.computers.NUVLA]: {
      runtime: 10800,
      nodes: 3,
      cpus: 8,
      executable: 'epfl-mooc/simulation/launch_simulation_parallel',
      environment: { NUVLA__worker__multiplicity: 4 },
    },
    [constants.computers.PIZ_DAINT]: {
      script: [
        '#!/bin/bash -l',
        '. /etc/profile',
        'module swap PrgEnv-cray PrgEnv-intel',
        'export MODULEPATH=/apps/hbp/ich002/hbp-spack-deployments/softwares/05-06-2019/install/modules/tcl/cray-cnl6-haswell:$MODULEPATH',
        'module load neurodamus-hippocampus/0.2 cray-python/2.7.15.1',
        'export FULL_CPU_PER_NODE=36',
        '/users/bp000037/simulation/simulation_launch.py -vv --blueconfig BlueConfig',
      ],
      runtime: 3600,
      nodes: 3,
      cpus: 36,
      executable: '/bin/bash input.sh',
      nodeType: 'mc',
      memory: 64000,
    },
    [constants.computers.BB5]: {
      script: [
        '#!/bin/bash -l',
        '. /etc/profile',
        'module purge',
        'module load nix/nse/bluepy-py3/0.13.4',
        'module load neurodamus-hippocampus/0.2/python3',
        'export FULL_CPU_PER_NODE=36',
        'python /gpfs/bbp.cscs.ch/home/antonel/scripts_unicore/simulation_launch_python3.py -vv --blueconfig BlueConfig',
      ],
      runtime: 3600,
      nodes: 2,
      cpus: 36,
      executable: '/bin/bash input.sh',
      project: '',
      memory: 32000,
      partitions: { '*': 'prod' },
    },
    defaultDuration: 300,
    defaultForwardSkip: 5000,
    importSimulationScript: 'ln -sf SIMFOLDERPATH/* .',
    stimuli: [
      { name: 'Linear', params: ['AmpStart', 'AmpEnd'] },
      { name: 'NPoisson', params: ['Lambda', 'Weight', 'NumOfSynapses'] },
      { name: 'Noise', params: ['MeanPercent', 'Variance'] },
    ],
    reportOn: {
      voltage: 'Voltage',
      calcium: 'Calcium Concentration',
      lfp: 'Total Current for LFP',
    },
    checksForLFP: ['AllCompartments', 'Summation'],
  },
  [constants.areas.SSCX]: {
    [constants.computers.BB5]: {
      script: [
        '#!/bin/bash -l',
        '. /etc/profile',
        'export HOC_LIBRARY_PATH=/gpfs/bbp.cscs.ch/project/proj1/src/bglib/release-2012.11.06-653-ge5acaf4_patchSynLoading',
        'srun $HOC_LIBRARY_PATH/powerpc64/special -NFRAME 256 $HOC_LIBRARY_PATH/init.hoc',
      ],
      runtime: 3600,
      nodes: 5,
      cpus: 36,
      executable: '/bin/bash input.sh',
      project: 'proj1',
      memory: 8000,
      partitions: { '*': 'prod' },
    },
    defaultDuration: 300,
    defaultForwardSkip: 5000,
    importSimulationScript: 'ln -sf SIMFOLDERPATH/* .',
    stimuli: [
      { name: 'Linear', params: ['AmpStart', 'AmpEnd'] },
      { name: 'NPoisson', params: ['Lambda', 'Weight', 'NumOfSynapses'] },
      { name: 'Noise', params: ['MeanPercent', 'Variance'] },
    ],
    reportOn: {
      voltage: 'Voltage',
      calcium: 'Calcium Concentration',
      lfp: 'Total Current for LFP',
    },
    checksForLFP: ['AllCompartments', 'Summation'],
  },
};
