
/* eslint-disable quote-props */
const mapper = {
  '5 Central Cells': '5Cells',
  'Full Circuit': 'Mosaic',
  'Entire Circuit': 'All',
  'Excitatory': 'Excitatory',
  'Inhibitory': 'Inhibitory',
  'Stratum Lacunosum Moleculare - Perforant Pathway Associated': 'SLM_PPA',
  'Stratum Oriens - Back Projecting': 'SO_BP',
  'Stratum Oriens - Bistratified': 'SO_BS',
  'Stratum Oriens - Oriens Lacunosum-Moleculare': 'SO_OLM',
  'Stratum Oriens - Trilaminar': 'SO_Tri',
  'Stratum Pyramidale - Axon Axonic': 'SP_AA',
  'Stratum Pyramidale - Bistratified': 'SP_BS',
  'Stratum Pyramidale - CCK positive Basket Cell': 'SP_CCKBC',
  'Stratum Pyramidale - Ivy cell': 'SP_Ivy',
  'Stratum Pyramidale - Pyramidal Cell': 'SP_PC',
  'Stratum Pyramidale - PV positive Basket Cell': 'SP_PVBC',
  'Stratum Radiatum - SCA': 'SR_SCA',
  'Bursting Accommodating': 'bAC',
  'Classical Accommodating': 'cAC',
  'Classical Accommodating for Pyramidal Cells': 'cACpyr',
  'Classical Non-Accommodating': 'cNAC',
  'Column 0 - Stratum Oriens': 'mc0;SO',
  'Column 0 - Stratum Pyramidale': 'mc0;SP',
  'Column 0 - Stratum Radiatum': 'mc0;SR',
  'Column 1 - Stratum Oriens': 'mc1;SO',
  'Column 1 - Stratum Pyramidale': 'mc1;SP',
  'Column 1 - Stratum Radiatum': 'mc1;SR',
  'Column 2 - Stratum Oriens': 'mc2;SO',
  'Column 2 - Stratum Pyramidale': 'mc2;SP',
  'Column 2 - Stratum Radiatum': 'mc2;SR',
  'Column 3 - Stratum Lacunosum Moleculare': 'mc3;SLM',
  'Column 3 - Stratum Oriens': 'mc3;SO',
  'Column 3 - Stratum Pyramidale': 'mc3;SP',
  'Column 3 - Stratum Radiatum': 'mc3;SR',
  'Column 4 - Stratum Oriens': 'mc4;SO',
  'Column 4 - Stratum Pyramidale': 'mc4;SP',
  'Column 4 - Stratum Radiatum': 'mc4;SR',
  'Column 5 - Stratum Lacunosum Moleculare': 'mc5;SLM',
  'Column 5 - Stratum Oriens': 'mc5;SO',
  'Column 5 - Stratum Pyramidale': 'mc5;SP',
  'Column 5 - Stratum Radiatum': 'mc5;SR',
  'Column 6 - Stratum Lacunosum Moleculare': 'mc6;SLM',
  'Column 6 - Stratum Oriens': 'mc6;SO',
  'Column 6 - Stratum Pyramidale': 'mc6;SP',
  'Column 6 - Stratum Radiatum': 'mc6;SR',
  'Column 0': 'mc0_Column',
  'Column 1': 'mc1_Column',
  'Central Column': 'mc2_Column',
  'Column 3': 'mc3_Column',
  'Column 4': 'mc4_Column',
  'Column 5': 'mc5_Column',
  'Column 6': 'mc6_Column',
  'Stratum Lacunosum Moleculare': 'SLM',
  'Stratum Oriens': 'SO',
  'Stratum Pyramidale': 'SP',
  'Stratum Radiatum': 'SR',
  '10 Cells from Stratum Pyramidale - Pyramidal Cell': 'most_central_10_SP_PC',
  '20 Cells from Stratum Pyramidale - Pyramidal Cell': 'most_central_20_SP_PC',
  '50 Cells from Stratum Pyramidale - Pyramidal Cell': 'most_central_50_SP_PC',
  '100 Cells from Stratum Pyramidale - Pyramidal Cell': 'most_central_100_SP_PC',
  'Somatostatin-Positive': 'SOM',
  'Cholecystokinin-Positive': 'CCK',
  'Parvalbumin-Positive': 'PV',
  'Basket Cell': 'BC',
  'Bistratified': 'BS',
  'CA3 Projection': 'CA3_PC',
};

export default mapper;
